---
title: "Study Overview"
---

## Lit Review
  Developmental reasearch has demonstrated that infants as young as 15-months recruit social information of a scene when making visual predictions (Krogh-Jesperesen, 2014). In an eye-tracking paradigm, infants are first familiarized to a video of a female agent acting on one of two toys. In test, infants view a scene in which the locations of the two toys have switched and the experimenter lifts her hand, but does not complete the reaching motion. Infants are said to make goal- or location-based predictions when they preferentially look to the previously grasped toy or previous location in which a reach was performed, respectively, after having first fixated on an area of interest defined about the agent's hand. When shown a video of actors either grasping or ambiguously brushing  one of two stuffed toys in familiarization, 15-month olds reliably made goal-based visual predictions for the grasping action, but not for the ambiguous brushing behavior. Additionally, on trials in which infants made visual predictions, goal-based predictions took longer to produce than location-based predictions. The theorectical explanation for this difference is that making goal-predictions are more cognitively challenging than making location-predictions because social information must be recruited and implemented to make a behavioral response. Given this difference in latency, infants' attention to the scene in familiarization has been suggested as a predictor of socially-relevant goal-based predictions, such that infants who spend more time attending to the scene in familiarization may be more able to detect the change in the test event to accurately predict continued action upon the prior object.  
  
  In the aforementioned study, a predition was defined as a gaze fixation to either object after a fixation to a pre-defined area of interest around the agent's hand. The current study seeks to confirm the previous findings that goal-based predictions take longer than location-based predictions to elicit while comparing the proportion of predictions made following either an initial fixation to an area of interest around the hand or to that which encompasses the agent's entire body. Additionally, the relationship between overall scene attention in familizarization and proportion of predictions generated on test will be explored. 
  
### Research Questions
#### * Q1: Does AOI definition matter?
#### * Q2: Does latency vary by type of prediction?
#### * Q3: Can attention to familiarization predict whether or not an infant will generate a prediction?
#### * Q4: Can attention to familiarization predict what type of prediction infants will generate when they do make a prediction?

## Method

### Eye-tracking Paradigm
  Eighteen-month-old infants were shown an eye-tracking paradigm as described above. Familiarization videos showed an agent reaching for and grasping one of two toys. Four different agents and toy-pairs were shown. Test trials were shown twice, each after familiarization, for a total of 8 Test Trials.

### Data Reduction



## Results

### Infant Generated Prediction

### Prediction Speed


  
